---
- name: Run CrowdStrike commands
  hosts: falcon_servers
  become: true
  gather_facts: false

  tasks:
    - name: Get falcon-sensor service status
      ansible.builtin.shell: systemctl status falcon-sensor
      register: falcon_status
      changed_when: false

    - name: Get Falcon version
      ansible.builtin.command: /opt/crowdstrike/falconctl -g --version
      register: falcon_version
      changed_when: false

    - name: Get Falcon RFM state
      ansible.builtin.command: /opt/crowdstrike/falconctl -g --rfm-state
      register: falcon_rfm
      changed_when: false

    - name: Print service status
      ansible.builtin.debug:
        msg: "{{ falcon_status.stdout }}"

    - name: Print Falcon version
      ansible.builtin.debug:
        msg: "{{ falcon_version.stdout }}"

    - name: Print Falcon RFM state
      ansible.builtin.debug:
        msg: "{{ falcon_rfm.stdout }}"
