---
- name: Collect CrowdStrike information
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Falcon service status
      ansible.builtin.command: systemctl status falcon-sensor
      register: falcon_status
      changed_when: false
      failed_when: false

    - name: Falcon version
      ansible.builtin.command: /opt/crowdstrike/falconctl -g --version
      register: falcon_version
      changed_when: false
      failed_when: false

    - name: Falcon RFM state
      ansible.builtin.command: /opt/crowdstrike/falconctl -g --rfm-state
      register: falcon_rfm
      changed_when: false
      failed_when: false

    - name: Display Falcon service status
      ansible.builtin.debug:
        var: falcon_status.stdout_lines

    - name: Display Falcon version
      ansible.builtin.debug:
        var: falcon_version.stdout_lines

    - name: Display Falcon RFM state
      ansible.builtin.debug:
        var: falcon_rfm.stdout_lines
